# Generated by Django 3.0.8 on 2020-07-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200709_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Skill_level'),
            preserve_default=False,
        ),
    ]
